# Tensorflow Basics

In [25]:
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'1.8.0'

In [3]:
a = tf.constant([[1,2,3], [4,5,6]])
b = tf.constant([[1,2,3], [4,5,6]])
c = a*b

In [4]:
print(c)

Tensor("mul:0", shape=(2, 3), dtype=int32)


In [9]:
#method-1
sess = tf.InteractiveSession()

C:\Users\GauravP\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [10]:
print(sess.run(c))

[[ 1  4  9]
 [16 25 36]]


In [26]:
#to print the shape
c.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [8]:
# method-2
with tf.Session() as sess:
    print(sess.run(c))

[[ 1  4  9]
 [16 25 36]]


In [18]:
#constant
d = tf.constant(10)
print(sess.run(d))

10


In [19]:
#fill
fill_mat = tf.fill([5,5], 10)
print(sess.run(fill_mat))

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [20]:
#zeros
ze = tf.zeros((4, 4))
print(sess.run(ze))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
#ones
on = tf.ones((4, 4))
print(sess.run(on))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
#random-1
rand1 = tf.random_normal((4, 4), mean=0, stddev=1.0)
print(sess.run(rand1))

[[ 0.08105621  1.6465145   2.3965821  -0.2628198 ]
 [-0.56336534  0.10079575 -0.13482164 -0.04026869]
 [ 2.3087816   0.90818655 -0.928697    0.34669408]
 [ 0.5370662  -1.3453203   1.071365   -1.139409  ]]


In [24]:
#random-2
rand2 = tf.random_uniform((4, 4), minval=0, maxval=1.0)
print(sess.run(rand2))

[[0.58645964 0.3296982  0.69560945 0.9811851 ]
 [0.42986047 0.7999072  0.8676853  0.8624598 ]
 [0.19724166 0.8118471  0.8605795  0.6136397 ]
 [0.7157414  0.43512964 0.6529598  0.08277678]]
