In [1]:
import tensorflow as tf

C:\Users\GauravP\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess = tf.InteractiveSession()

In [3]:
my_tensor = tf.random_uniform((4, 4), 0, 1)

In [4]:
my_tensor

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [5]:
sess.run(my_tensor)

array([[0.97159433, 0.83924365, 0.58760357, 0.64943933],
       [0.7465607 , 0.61668634, 0.59554875, 0.08819878],
       [0.15731812, 0.64224565, 0.15906858, 0.17816532],
       [0.1389302 , 0.83112156, 0.1218338 , 0.06259894]], dtype=float32)

In [6]:
my_var = tf.Variable(initial_value = my_tensor)
my_var

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>

In [8]:
sess.run(tf.global_variables_initializer())

In [9]:
sess.run(my_var)

array([[0.38519514, 0.6413573 , 0.10132658, 0.33583975],
       [0.16773856, 0.11256933, 0.52229166, 0.81627536],
       [0.832754  , 0.29169905, 0.8390322 , 0.02041578],
       [0.61575186, 0.20766795, 0.44183064, 0.41540623]], dtype=float32)

In [10]:
ph = tf.placeholder(tf.float32, shape=(None, 4))
ph

<tf.Tensor 'Placeholder:0' shape=(?, 4) dtype=float32>

In [11]:
ph = my_var

In [12]:
sess.run(ph)

array([[0.38519514, 0.6413573 , 0.10132658, 0.33583975],
       [0.16773856, 0.11256933, 0.52229166, 0.81627536],
       [0.832754  , 0.29169905, 0.8390322 , 0.02041578],
       [0.61575186, 0.20766795, 0.44183064, 0.41540623]], dtype=float32)

In [15]:
ph = tf.random_uniform((6, 4), 2, 5)
sess.run(ph)

array([[4.042366 , 2.0588741, 2.1981566, 2.2574797],
       [2.04881  , 3.2237296, 3.6658826, 3.2365756],
       [4.8010483, 3.613798 , 3.9730792, 2.0212913],
       [2.1396809, 4.8787556, 2.3624878, 3.5138552],
       [3.4825096, 4.49986  , 4.1768584, 4.222689 ],
       [2.9309587, 3.4883933, 2.23637  , 2.94072  ]], dtype=float32)